package daar.testcases.com;

import org.apache.log4j.xml.DOMConfigurator;
import org.testng.Assert;
import org.testng.annotations.Test;
import org.w3c.dom.DOMConfiguration;

import qf.appmethods.com.LeadsMethods;
import qf.pom.com.Leads;
import qf.repository.com.LeadData;
import qf.repository.com.Properties;
import qf.utility.com.Log;

public class qf_TC08_ManualLeadProcess extends LeadsMethods {
	@Test
	public void qf_manuallead() throws Exception 
	{
		DOMConfigurator.configure("log.xml");
		Log.startTestCase("---Lead Process Start---");
		
		Log.info("Step 1: Open lead Module");
		Assert.assertTrue(Leads.nav_LeadModule.isDisplayed(), "Failed : Lead Module not found !!!");
		click_leadmodule();
		common.takeSnapShot("Leadasperstatus", "OpenLeadModule.png");
		
		Log.info("Step 2: Click on Add new Lead icon");
		Assert.assertTrue(Leads.icon_new.isDisplayed(), "Failed : Add new Lead icon is not found");
		click_leadiconnew();
		common.takeSnapShot("Leadasperstatus","Addnewleadicon.png");
		
		Log.info("Step 3: Select Lead Salutation");
		Assert.assertTrue(Leads.dropdown_leadsalutation.isDisplayed(), "Failed : Saluation filed is not found.");
		select_leadsalutaion(LeadData.leadsalutaion);
		Assert.assertFalse(Leads.dropdown_leadsalutation.getAttribute("value").equalsIgnoreCase(""), "Failed : No value filled in saluation..");
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadsalutaion);
//		enter_leadfirstname(LeadData.leadfirstnamenewstatus);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadfirstname);
//		enter_leadmiddlename(LeadData.leadmiddlename);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadmiddlename);
//		enter_leadlastname(LeadData.leadlastname);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadlastname);
//		enter_leaddob();
//		common.takeSnapShot(driver, Properties.qf_UI_val_leaddob);
//		select_leadgender(LeadData.leadgender);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadgender);
//		enter_leadmobile(LeadData.leadmobile);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadmobile);
//		select_leadnationality(LeadData.leadnationality);
//		enter_leadcity(LeadData.leadcity);
//		select_leadschemaname(LeadData.leadschemaname);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadnationality);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadcity);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadschemaname);
//		select_leadrating(LeadData.leadrating);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadrating);
//		select_leadstatus(LeadData.leadstatusnew);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadstatus);
//		select_leademaploymenttype(LeadData.leademaploymenttype);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leademaploymenttype);
//		enter_leadmonthlysalary(LeadData.leadmonthlysalary);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadmonthlysalary);
//		enter_leadloanamount(LeadData.leadloanamount);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadloanamount);
//		select_leadtypeoffinance(LeadData.leadtypeoffinance);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadtypeoffinance);
//		select_leadanyexistingloan(LeadData.leadanyexistingloan);
//		enter_leadremarks(LeadData.leadremarks);
//		common.scrolldown();
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadremarks);
//		select_leadproductsubtype(LeadData.leadproductsubtype);
//		common.takeSnapShot(driver, Properties.qf_UI_val_leadproductsubtype);
//		click_leadsave();
//		//Validate Status as New
//		validate_leadasnew();
//		//Pick Lead ID which is an autogenerated unique value
//		pick_leadid();
//		common.takeSnapShot(driver, Properties.qf_UI_leaddetailpage_new);
//		//Search New Created lead via Lead Search
//		click_quicklink();
//		click_leadsearch();
//		enter_leadIDtobesearched(LeadID);
//		common.takeSnapShot(driver, Properties.qf_UI_val_newcreatedlead_search);
//		click_search();
//		common.takeSnapShot(driver, Properties.qf_UI_searchedlist_newcreatedlead);
//		refres_page();
//		//Update Lead At Inprogress status from New
//		click_leadmodule();
//		click_arrowinleadview();
//		select_leadview(LeadData.NewLeadView);
//		click_searchiconunderleadview();
//		select_searchbyfield(LeadData.LeadToBeSearchInView);
//		enter_leadidinsearchby(LeadID);
//		common.takeSnapShot(driver, Properties.qf_UI_newleadview_searchnewcreatedlead);
//		click_searchedlead();
//		common.scrolldown();
//		click_editlead();
//		common.scrolldown();
//		select_leadstatus(LeadData.leadstatusinprogress);
//		common.takeSnapShot(driver, Properties.qf_UI_edit_searchnewcreatedlead);
//		click_leadsave();
//		//After updation validate lead status as inprogress
//		validate_leadasinprogress();
//		common.takeSnapShot(driver, Properties.qf_UI_leaddetailpage_inprogress);
//		//Update lead from Closed status from inprogress
//		click_leadmodule();
//		click_arrowinleadview();
//		select_leadview(LeadData.InProgressLeadView);
//		click_searchiconunderleadview();
//		select_searchbyfield(LeadData.LeadToBeSearchInView);
//		enter_leadidinsearchby(LeadID);
//		common.takeSnapShot(driver, Properties.qf_UI_inprogressleadview_searchupdatedinprogresslead);
//		click_searchedlead();
//		common.scrolldown();
//		click_editlead();
//		common.scrolldown();
//		select_leadstatus(LeadData.leadstatusclosed);
//		common.takeSnapShot(driver, Properties.qf_UI_edit_searchupdatedinprogresslead);
//		click_leadsave();
//		//After updation validate lead status as closed
//		validate_leadasclosed();
//		common.takeSnapShot(driver, Properties.qf_UI_leaddetailpage_closed);
//		//After updation closed lead should be shown in respective view
//		click_leadmodule();
//		click_arrowinleadview();
//		select_leadview(LeadData.CloseedLeadView);
//		click_searchiconunderleadview();
//		select_searchbyfield(LeadData.LeadToBeSearchInView);
//		enter_leadidinsearchby(LeadID);
//		common.takeSnapShot(driver, Properties.qf_UI_inprogressleadview_searchupdatedclosedlead);
//		click_searchedlead();
	}
}
